# Generated by Django 4.2 on 2025-02-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GymMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.CharField(max_length=50, unique=True)),
                ("expiry", models.DateField()),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("join_date", models.DateField(auto_now_add=True)),
                ("renewed", models.BooleanField(default=False)),
                ("profile_image", models.ImageField(upload_to="images/")),
            ],
            options={
                "db_table": "gym_members",
            },
        ),
        migrations.CreateModel(
            name="LoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("login_time", models.CharField(max_length=100)),
                ("login_date", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "gym_login_record",
                "unique_together": {("id_card", "login_date")},
            },
        ),
    ]
