# Generated by Django 4.2 on 2025-02-19 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sale_function", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="product_table",
        ),
    ]
