# Generated by Django 4.2 on 2025-02-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale_function", "0002_alter_product_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
