# Generated by Django 4.2 on 2025-02-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettingColorTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("active", models.BooleanField()),
            ],
            options={
                "db_table": "setting_color_table",
            },
        ),
        migrations.CreateModel(
            name="SettingFontTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("active", models.BooleanField()),
            ],
            options={
                "db_table": "setting_font_table",
            },
        ),
    ]
