# Generated by Django 4.2 on 2025-02-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("function_gym", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gymsale",
            old_name="sale_price",
            new_name="total_sale",
        ),
        migrations.AddField(
            model_name="productitem",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "gym_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="function_gym.gymsale",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="function_gym.productitem",
                    ),
                ),
            ],
        ),
    ]
